version: "3.4"
services:
  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - network-example

  backend:
    build: ./backend/.
    networks:
      - network-example
    ports:
      - 3001:3001
    depends_on:
      rabbitmq3:
        condition: service_healthy

  front-end:
    build: ./client/.
    networks:
      - network-example
    ports:
      - 3000:3000
    depends_on:
      - backend




networks:
  network-example:
    external: true
